=== TatyOlmedo/SOA_TatianaOlmedo/SOA_TatianaOlmedo/ejercicio2/ejercicio2_personas.xsd
<xsd:schema version="1.0"
           xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xsd:annotation>
        <xsd:documentation>
            Diseno de schema de ejercicio2_personas.xml
        </xsd:documentation>
    </xsd:annotation>

    <xsd:element name="genero">
        <xsd:complexType>
            <xsd:choice>
                <xsd:element name="hombre" type="xsd:string"/>
                <xsd:element name="mujer" type="xsd:string"/>
            </xsd:choice>
        </xsd:complexType>
    </xsd:element> 
    
    
    <xsd:element name="nacimiento">
        <xsd:complexType>                  
            <xsd:attribute name="dia" type="tipoDia"/>
            <xsd:attribute name="mes" type="tipoMes"/>
            <xsd:attribute name="anio" type="tipoAnio"/>                    
        </xsd:complexType>
    </xsd:element>
    
    
    <xsd:simpleType name="tipoDia">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1"/>
            <xsd:maxInclusive value="31"/>
        </xsd:restriction>
    </xsd:simpleType> 
    
    <xsd:simpleType name="tipoMes">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Enero"/>
            <xsd:enumeration value="Febrero"/>
            <xsd:enumeration value="Marzo"/>
            <xsd:enumeration value="Abril"/>
            <xsd:enumeration value="Mayo"/>
            <xsd:enumeration value="Junio"/>
            <xsd:enumeration value="Julio"/>
            <xsd:enumeration value="Agosto"/>
            <xsd:enumeration value="Septiembre"/>
            <xsd:enumeration value="Octubre"/>
            <xsd:enumeration value="Noviembre"/>
            <xsd:enumeration value="Diciembre"/>
        </xsd:restriction>
    </xsd:simpleType> 


    <xsd:simpleType name="tipoAnio">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1900"/>
            <xsd:maxInclusive value="2015"/>
        </xsd:restriction>
    </xsd:simpleType> 
    
    <xsd:simpleType name="tipoNombre">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="50"/>
        </xsd:restriction>
    </xsd:simpleType> 
    
    <xsd:element name="nombre" type="tipoNombre"/>
    <xsd:element name="call" type="tipoNombre"/>
    <xsd:element name="ciudad" type="tipoNombre"/>
    <xsd:element name="provincia" type="tipoNombre"/>
    <xsd:element name="pai" type="tipoNombre"/>
    
    
    <xsd:element name="direccion">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="call" maxOccurs="unbounded" />
                <xsd:element ref="ciudad" />
                <xsd:element ref="provincia" />
                <xsd:element ref="pai" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element> 
    
   
    
    <xsd:element name="personas">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="persona" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="persona">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nombre"/>
                <xsd:element ref="nacimiento" minOccurs="0" maxOccurs="1"/>
                <xsd:element ref="direccion" maxOccurs="unbounded"/> 
                <xsd:element ref="genero" maxOccurs="1"/> 
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element> 
</xsd:schema>

=== TatyOlmedo/SOA_TatianaOlmedo/SOA_TatianaOlmedo/ejercicio2/ejercicio2_personas.xml
<?xml version="1.0" encoding="UTF-8"?>

<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="ejercicio2_personas.xsd">
    
   
<persona>
    <nombre>Juan Perez</nombre>
    <nacimiento dia="3" mes="Mayo" anio="1986"/>
    <direccion>
       <call>12 de Octubre y General Foch</call>
       <ciudad>Quito</ciudad>
       <provincia>Pichincha</provincia>
       <pai>Ecuador</pai>
    </direccion>
    <genero>
      <hombre/>  
    </genero>
 </persona>
 
 <persona>
    <nombre>María López</nombre>
    <direccion>
       <call>Tamayo n12 y Francisco Salazar</call>
       <ciudad>Quito</ciudad>
       <provincia>Pichincha</provincia>
       <pai>Ecuador</pai>
    </direccion>
    <direccion>
       <call>Pichincha 605 entre Clemente Ballén y 10 de Agosto</call>
       <ciudad>Guayaquil</ciudad>
       <provincia>Guayas</provincia>
       <pai>Ecuador</pai>
    </direccion>
    <genero>        
    <mujer/>
    </genero>
 </persona>
</personas>
